# --- Dropdown Options ---
# TODO: Add more equipment options here
EQUIPMENT_OPTIONS = [
    "Termómetro",
    "Multímetro",
    "Espectrómetro",
    "Cámara térmica",
    "Osciloscopio",
    "Generador de señales",
    "Analizador de potencia",
    "Medidor de corriente",
    "Sensor de temperatura",
    "Equipo de calibración",
    "Otro"  # Placeholder for additional options
]

# TODO: Add more brand/model options here
MARCA_OPTIONS = [
    "Fluke",
    "Agilent",
    "Keysight",
    "Tektronix",
    "National Instruments",
    "Omega",
    "Testo",
    "Extech",
    "Rigol",
    "Otro"  # Placeholder for additional options
]

# TODO: Add more type/application options here
TIPO_OPTIONS = [
    "Digital",
    "Analógico",
    "Infrarrojo",
    "Contacto",
    "No contacto",
    "Portátil",
    "De mesa",
    "Automático",
    "Manual",
    "Otro"  # Placeholder for additional options
]

# TODO: Add more method options here
METHOD_OPTIONS = [
    "IEC 60598",
    "EN 60598",
    "UL 1993",
    "IEC 61347",
    "Otro"  # Placeholder for additional options
]

# Temperature measurement point options
PUNTO_OPTIONS = [
    "Base del LED",
    "Driver",
    "Housing",
    "Lens",
    "PCB",
    "Terminal",
    "Cable",
    "Otro"
]

# Temperature unit options
UNIDAD_OPTIONS = [
    "°C",
    "°F",
    "K"
]

# Common temperature limits
LIMITE_OPTIONS = [
    "80°C",
    "90°C",
    "100°C",
    "110°C",
    "120°C",
    "Otro"
]

# Result options
RESULT_OPTIONS = [
    "Pass",
    "N/A"
]

# --- Definisi Placeholders & Input Fields ---
FIELD_DEFINITIONS = {
    # Header fields
    "NO_TEST": {"placeholder": "[NO_TEST]", "label": "Nº de Test Plan", "type": "text"},
    "REV": {"placeholder": "[REV]", "label": "Revisión", "type": "text"},
    "DATE": {"placeholder": "[DATE]", "label": "Fecha de emisión (DD/MM/YYYY)", "type": "date"},

    # 0. INFORMACIÓN DEL SOLICITANTE DEL ENSAYO
    "TEXT1": {"placeholder": "[TEXT1]", "label": "Solicitante", "type": "text"},
    "TEXT4": {"placeholder": "[TEXT4]", "label": "Operario del ensayo", "type": "text"},
    "TEXT2": {"placeholder": "[TEXT2]", "label": "Departamento", "type": "text"},
    "TEXT5": {"placeholder": "[TEXT5]", "label": "Responsable del ensayo", "type": "text"},
    "TEXT3": {"placeholder": "[TEXT3]", "label": "Fecha de solicitud (DD/MM/YYYY)", "type": "date"},

    # 1. INFORMACIÓN GENERAL DEL PRODUCTO
    "TEXT6": {"placeholder": "[TEXT6]", "label": "Referencia del modelo ensayado", "type": "text"},
    "TEXT7": {"placeholder": "[TEXT7]", "label": "Aplicación", "type": "text"},
    "TEXT8": {"placeholder": "[TEXT8]", "label": "Fuente de luz", "type": "text"},

    # 1.1. CONDICIONES DEL ENSAYO
    "TEXT9": {"placeholder": "[TEXT9]", "label": "Ensayo térmico realizado en", "type": "text"},
    "TEXT10": {"placeholder": "[TEXT10]", "label": "Temperatura de color ensayada (CCT)", "type": "text"},
    "TEXT11": {"placeholder": "[TEXT11]", "label": "Luminaria alimentada a", "type": "text"},

    # 2. EQUIPOS Y MÉTODOS UTILIZADOS (up to 12)
    "EQUIPO1": {"placeholder": "[EQUIPO1]", "label": "Equipo 1", "type": "dropdown", "options": EQUIPMENT_OPTIONS},
    "MARCA1": {"placeholder": "[MARCA1]", "label": "Marca/Modelo 1", "type": "dropdown", "options": MARCA_OPTIONS},
    "TIPO1": {"placeholder": "[TIPO1]", "label": "Tipo/Aplicación 1", "type": "dropdown", "options": TIPO_OPTIONS},
    "FECHA1": {"placeholder": "[FECHA1]", "label": "Fecha de calibración 1", "type": "date"},
    "OBSER1": {"placeholder": "[OBSER1]", "label": "Observaciones 1", "type": "text"},
    "EQUIPO2": {"placeholder": "[EQUIPO2]", "label": "Equipo 2", "type": "dropdown", "options": EQUIPMENT_OPTIONS},
    "MARCA2": {"placeholder": "[MARCA2]", "label": "Marca/Modelo 2", "type": "dropdown", "options": MARCA_OPTIONS},
    "TIPO2": {"placeholder": "[TIPO2]", "label": "Tipo/Aplicación 2", "type": "dropdown", "options": TIPO_OPTIONS},
    "FECHA2": {"placeholder": "[FECHA2]", "label": "Fecha de calibración 2", "type": "date"},
    "OBSER2": {"placeholder": "[OBSER2]", "label": "Observaciones 2", "type": "text"},
    "EQUIPO3": {"placeholder": "[EQUIPO3]", "label": "Equipo 3", "type": "dropdown", "options": EQUIPMENT_OPTIONS},
    "MARCA3": {"placeholder": "[MARCA3]", "label": "Marca/Modelo 3", "type": "dropdown", "options": MARCA_OPTIONS},
    "TIPO3": {"placeholder": "[TIPO3]", "label": "Tipo/Aplicación 3", "type": "dropdown", "options": TIPO_OPTIONS},
    "FECHA3": {"placeholder": "[FECHA3]", "label": "Fecha de calibración 3", "type": "date"},
    "OBSER3": {"placeholder": "[OBSER3]", "label": "Observaciones 3", "type": "text"},
    "EQUIPO4": {"placeholder": "[EQUIPO4]", "label": "Equipo 4", "type": "dropdown", "options": EQUIPMENT_OPTIONS},
    "MARCA4": {"placeholder": "[MARCA4]", "label": "Marca/Modelo 4", "type": "dropdown", "options": MARCA_OPTIONS},
    "TIPO4": {"placeholder": "[TIPO4]", "label": "Tipo/Aplicación 4", "type": "dropdown", "options": TIPO_OPTIONS},
    "FECHA4": {"placeholder": "[FECHA4]", "label": "Fecha de calibración 4", "type": "date"},
    "OBSER4": {"placeholder": "[OBSER4]", "label": "Observaciones 4", "type": "text"},
    "EQUIPO5": {"placeholder": "[EQUIPO5]", "label": "Equipo 5", "type": "dropdown", "options": EQUIPMENT_OPTIONS},
    "MARCA5": {"placeholder": "[MARCA5]", "label": "Marca/Modelo 5", "type": "dropdown", "options": MARCA_OPTIONS},
    "TIPO5": {"placeholder": "[TIPO5]", "label": "Tipo/Aplicación 5", "type": "dropdown", "options": TIPO_OPTIONS},
    "FECHA5": {"placeholder": "[FECHA5]", "label": "Fecha de calibración 5", "type": "date"},
    "OBSER5": {"placeholder": "[OBSER5]", "label": "Observaciones 5", "type": "text"},
    "EQUIPO6": {"placeholder": "[EQUIPO6]", "label": "Equipo 6", "type": "dropdown", "options": EQUIPMENT_OPTIONS},
    "MARCA6": {"placeholder": "[MARCA6]", "label": "Marca/Modelo 6", "type": "dropdown", "options": MARCA_OPTIONS},
    "TIPO6": {"placeholder": "[TIPO6]", "label": "Tipo/Aplicación 6", "type": "dropdown", "options": TIPO_OPTIONS},
    "FECHA6": {"placeholder": "[FECHA6]", "label": "Fecha de calibración 6", "type": "date"},
    "OBSER6": {"placeholder": "[OBSER6]", "label": "Observaciones 6", "type": "text"},
    "EQUIPO7": {"placeholder": "[EQUIPO7]", "label": "Equipo 7", "type": "dropdown", "options": EQUIPMENT_OPTIONS},
    "MARCA7": {"placeholder": "[MARCA7]", "label": "Marca/Modelo 7", "type": "dropdown", "options": MARCA_OPTIONS},
    "TIPO7": {"placeholder": "[TIPO7]", "label": "Tipo/Aplicación 7", "type": "dropdown", "options": TIPO_OPTIONS},
    "FECHA7": {"placeholder": "[FECHA7]", "label": "Fecha de calibración 7", "type": "date"},
    "OBSER7": {"placeholder": "[OBSER7]", "label": "Observaciones 7", "type": "text"},
    "EQUIPO8": {"placeholder": "[EQUIPO8]", "label": "Equipo 8", "type": "dropdown", "options": EQUIPMENT_OPTIONS},
    "MARCA8": {"placeholder": "[MARCA8]", "label": "Marca/Modelo 8", "type": "dropdown", "options": MARCA_OPTIONS},
    "TIPO8": {"placeholder": "[TIPO8]", "label": "Tipo/Aplicación 8", "type": "dropdown", "options": TIPO_OPTIONS},
    "FECHA8": {"placeholder": "[FECHA8]", "label": "Fecha de calibración 8", "type": "date"},
    "OBSER8": {"placeholder": "[OBSER8]", "label": "Observaciones 8", "type": "text"},
    "EQUIPO9": {"placeholder": "[EQUIPO9]", "label": "Equipo 9", "type": "dropdown", "options": EQUIPMENT_OPTIONS},
    "MARCA9": {"placeholder": "[MARCA9]", "label": "Marca/Modelo 9", "type": "dropdown", "options": MARCA_OPTIONS},
    "TIPO9": {"placeholder": "[TIPO9]", "label": "Tipo/Aplicación 9", "type": "dropdown", "options": TIPO_OPTIONS},
    "FECHA9": {"placeholder": "[FECHA9]", "label": "Fecha de calibración 9", "type": "date"},
    "OBSER9": {"placeholder": "[OBSER9]", "label": "Observaciones 9", "type": "text"},
    "EQUIPO10": {"placeholder": "[EQUIPO10]", "label": "Equipo 10", "type": "dropdown", "options": EQUIPMENT_OPTIONS},
    "MARCA10": {"placeholder": "[MARCA10]", "label": "Marca/Modelo 10", "type": "dropdown", "options": MARCA_OPTIONS},
    "TIPO10": {"placeholder": "[TIPO10]", "label": "Tipo/Aplicación 10", "type": "dropdown", "options": TIPO_OPTIONS},
    "FECHA10": {"placeholder": "[FECHA10]", "label": "Fecha de calibración 10", "type": "date"},
    "OBSER10": {"placeholder": "[OBSER10]", "label": "Observaciones 10", "type": "text"},
    "EQUIPO11": {"placeholder": "[EQUIPO11]", "label": "Equipo 11", "type": "dropdown", "options": EQUIPMENT_OPTIONS},
    "MARCA11": {"placeholder": "[MARCA11]", "label": "Marca/Modelo 11", "type": "dropdown", "options": MARCA_OPTIONS},
    "TIPO11": {"placeholder": "[TIPO11]", "label": "Tipo/Aplicación 11", "type": "dropdown", "options": TIPO_OPTIONS},
    "FECHA11": {"placeholder": "[FECHA11]", "label": "Fecha de calibración 11", "type": "date"},
    "OBSER11": {"placeholder": "[OBSER11]", "label": "Observaciones 11", "type": "text"},
    "EQUIPO12": {"placeholder": "[EQUIPO12]", "label": "Equipo 12", "type": "dropdown", "options": EQUIPMENT_OPTIONS},
    "MARCA12": {"placeholder": "[MARCA12]", "label": "Marca/Modelo 12", "type": "dropdown", "options": MARCA_OPTIONS},
    "TIPO12": {"placeholder": "[TIPO12]", "label": "Tipo/Aplicación 12", "type": "dropdown", "options": TIPO_OPTIONS},
    "FECHA12": {"placeholder": "[FECHA12]", "label": "Fecha de calibración 12", "type": "date"},
    "OBSER12": {"placeholder": "[OBSER12]", "label": "Observaciones 12", "type": "text"},
    "TEXT12": {"placeholder": "[TEXT12]", "label": "Método de ensayo", "type": "text"},

    # 3. TEMPERATURAS REGISTRADAS (up to 10)
    "PUNTO1": {"placeholder": "[PUNTO1]", "label": "Punto de Medición 1", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNIDAD1": {"placeholder": "[UNIDAD1]", "label": "Unidad 1", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "LIMITE1": {"placeholder": "[LIMITE1]", "label": "Límite Máximo 1", "type": "dropdown", "options": LIMITE_OPTIONS},
    "TEMP1": {"placeholder": "[TEMP1]", "label": "Temperatura Medida 1", "type": "text"},
    "PUNTO2": {"placeholder": "[PUNTO2]", "label": "Punto de Medición 2", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNIDAD2": {"placeholder": "[UNIDAD2]", "label": "Unidad 2", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "LIMITE2": {"placeholder": "[LIMITE2]", "label": "Límite Máximo 2", "type": "dropdown", "options": LIMITE_OPTIONS},
    "TEMP2": {"placeholder": "[TEMP2]", "label": "Temperatura Medida 2", "type": "text"},
    "PUNTO3": {"placeholder": "[PUNTO3]", "label": "Punto de Medición 3", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNIDAD3": {"placeholder": "[UNIDAD3]", "label": "Unidad 3", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "LIMITE3": {"placeholder": "[LIMITE3]", "label": "Límite Máximo 3", "type": "dropdown", "options": LIMITE_OPTIONS},
    "TEMP3": {"placeholder": "[TEMP3]", "label": "Temperatura Medida 3", "type": "text"},
    "PUNTO4": {"placeholder": "[PUNTO4]", "label": "Punto de Medición 4", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNIDAD4": {"placeholder": "[UNIDAD4]", "label": "Unidad 4", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "LIMITE4": {"placeholder": "[LIMITE4]", "label": "Límite Máximo 4", "type": "dropdown", "options": LIMITE_OPTIONS},
    "TEMP4": {"placeholder": "[TEMP4]", "label": "Temperatura Medida 4", "type": "text"},
    "PUNTO5": {"placeholder": "[PUNTO5]", "label": "Punto de Medición 5", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNIDAD5": {"placeholder": "[UNIDAD5]", "label": "Unidad 5", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "LIMITE5": {"placeholder": "[LIMITE5]", "label": "Límite Máximo 5", "type": "dropdown", "options": LIMITE_OPTIONS},
    "TEMP5": {"placeholder": "[TEMP5]", "label": "Temperatura Medida 5", "type": "text"},
    "PUNTO6": {"placeholder": "[PUNTO6]", "label": "Punto de Medición 6", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNIDAD6": {"placeholder": "[UNIDAD6]", "label": "Unidad 6", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "LIMITE6": {"placeholder": "[LIMITE6]", "label": "Límite Máximo 6", "type": "dropdown", "options": LIMITE_OPTIONS},
    "TEMP6": {"placeholder": "[TEMP6]", "label": "Temperatura Medida 6", "type": "text"},
    "PUNTO7": {"placeholder": "[PUNTO7]", "label": "Punto de Medición 7", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNIDAD7": {"placeholder": "[UNIDAD7]", "label": "Unidad 7", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "LIMITE7": {"placeholder": "[LIMITE7]", "label": "Límite Máximo 7", "type": "dropdown", "options": LIMITE_OPTIONS},
    "TEMP7": {"placeholder": "[TEMP7]", "label": "Temperatura Medida 7", "type": "text"},
    "PUNTO8": {"placeholder": "[PUNTO8]", "label": "Punto de Medición 8", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNIDAD8": {"placeholder": "[UNIDAD8]", "label": "Unidad 8", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "LIMITE8": {"placeholder": "[LIMITE8]", "label": "Límite Máximo 8", "type": "dropdown", "options": LIMITE_OPTIONS},
    "TEMP8": {"placeholder": "[TEMP8]", "label": "Temperatura Medida 8", "type": "text"},
    "PUNTO9": {"placeholder": "[PUNTO9]", "label": "Punto de Medición 9", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNIDAD9": {"placeholder": "[UNIDAD9]", "label": "Unidad 9", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "LIMITE9": {"placeholder": "[LIMITE9]", "label": "Límite Máximo 9", "type": "dropdown", "options": LIMITE_OPTIONS},
    "TEMP9": {"placeholder": "[TEMP9]", "label": "Temperatura Medida 9", "type": "text"},
    "PUNTO10": {"placeholder": "[PUNTO10]", "label": "Punto de Medición 10", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNIDAD10": {"placeholder": "[UNIDAD10]", "label": "Unidad 10", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "LIMITE10": {"placeholder": "[LIMITE10]", "label": "Límite Máximo 10", "type": "dropdown", "options": LIMITE_OPTIONS},
    "TEMP10": {"placeholder": "[TEMP10]", "label": "Temperatura Medida 10", "type": "text"},
    "TEXT13": {"placeholder": "[TEXT13]", "label": "NOTA", "type": "text"},
    "TEXT14": {"placeholder": "[TEXT14]", "label": "Description", "type": "text"},
    "TEXT15": {"placeholder": "[TEXT15]", "label": "Conclusions", "type": "text"},

    # 3.1. GRÁFICA GENERADA
    "IMAGE1": {"placeholder": "[IMAGE1]", "label": "Imagen 1", "type": "file"},
    "TITLE1": {"placeholder": "[TITLE1]", "label": "Título 1", "type": "text"},
    "DESC1": {"placeholder": "[DESC1]", "label": "Descripción 1", "type": "text"},
    "IMAGE2": {"placeholder": "[IMAGE2]", "label": "Imagen 2", "type": "file"},
    "DESC2": {"placeholder": "[DESC2]", "label": "Descripción 2", "type": "text"},

    # 4. ESTABILIZACIÓN TÉRMICA (up to 10)
    "MEDICI1": {"placeholder": "[MEDICI1]", "label": "Punto de Medición 1", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNI1": {"placeholder": "[UNI1]", "label": "Unidad 1", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "VALMIN1": {"placeholder": "[VALMIN1]", "label": "Valor Mínimo 1", "type": "text"},
    "VALMAX1": {"placeholder": "[VALMAX1]", "label": "Valor Máximo 1", "type": "text"},
    "DESVI1": {"placeholder": "[DESVI1]", "label": "Desviación 1", "type": "text"},
    "MEDICI2": {"placeholder": "[MEDICI2]", "label": "Punto de Medición 2", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNI2": {"placeholder": "[UNI2]", "label": "Unidad 2", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "VALMIN2": {"placeholder": "[VALMIN2]", "label": "Valor Mínimo 2", "type": "text"},
    "VALMAX2": {"placeholder": "[VALMAX2]", "label": "Valor Máximo 2", "type": "text"},
    "DESVI2": {"placeholder": "[DESVI2]", "label": "Desviación 2", "type": "text"},
    "MEDICI3": {"placeholder": "[MEDICI3]", "label": "Punto de Medición 3", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNI3": {"placeholder": "[UNI3]", "label": "Unidad 3", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "VALMIN3": {"placeholder": "[VALMIN3]", "label": "Valor Mínimo 3", "type": "text"},
    "VALMAX3": {"placeholder": "[VALMAX3]", "label": "Valor Máximo 3", "type": "text"},
    "DESVI3": {"placeholder": "[DESVI3]", "label": "Desviación 3", "type": "text"},
    "MEDICI4": {"placeholder": "[MEDICI4]", "label": "Punto de Medición 4", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNI4": {"placeholder": "[UNI4]", "label": "Unidad 4", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "VALMIN4": {"placeholder": "[VALMIN4]", "label": "Valor Mínimo 4", "type": "text"},
    "VALMAX4": {"placeholder": "[VALMAX4]", "label": "Valor Máximo 4", "type": "text"},
    "DESVI4": {"placeholder": "[DESVI4]", "label": "Desviación 4", "type": "text"},
    "MEDICI5": {"placeholder": "[MEDICI5]", "label": "Punto de Medición 5", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNI5": {"placeholder": "[UNI5]", "label": "Unidad 5", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "VALMIN5": {"placeholder": "[VALMIN5]", "label": "Valor Mínimo 5", "type": "text"},
    "VALMAX5": {"placeholder": "[VALMAX5]", "label": "Valor Máximo 5", "type": "text"},
    "DESVI5": {"placeholder": "[DESVI5]", "label": "Desviación 5", "type": "text"},
    "MEDICI6": {"placeholder": "[MEDICI6]", "label": "Punto de Medición 6", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNI6": {"placeholder": "[UNI6]", "label": "Unidad 6", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "VALMIN6": {"placeholder": "[VALMIN6]", "label": "Valor Mínimo 6", "type": "text"},
    "VALMAX6": {"placeholder": "[VALMAX6]", "label": "Valor Máximo 6", "type": "text"},
    "DESVI6": {"placeholder": "[DESVI6]", "label": "Desviación 6", "type": "text"},
    "MEDICI7": {"placeholder": "[MEDICI7]", "label": "Punto de Medición 7", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNI7": {"placeholder": "[UNI7]", "label": "Unidad 7", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "VALMIN7": {"placeholder": "[VALMIN7]", "label": "Valor Mínimo 7", "type": "text"},
    "VALMAX7": {"placeholder": "[VALMAX7]", "label": "Valor Máximo 7", "type": "text"},
    "DESVI7": {"placeholder": "[DESVI7]", "label": "Desviación 7", "type": "text"},
    "MEDICI8": {"placeholder": "[MEDICI8]", "label": "Punto de Medición 8", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNI8": {"placeholder": "[UNI8]", "label": "Unidad 8", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "VALMIN8": {"placeholder": "[VALMIN8]", "label": "Valor Mínimo 8", "type": "text"},
    "VALMAX8": {"placeholder": "[VALMAX8]", "label": "Valor Máximo 8", "type": "text"},
    "DESVI8": {"placeholder": "[DESVI8]", "label": "Desviación 8", "type": "text"},
    "MEDICI9": {"placeholder": "[MEDICI9]", "label": "Punto de Medición 9", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNI9": {"placeholder": "[UNI9]", "label": "Unidad 9", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "VALMIN9": {"placeholder": "[VALMIN9]", "label": "Valor Mínimo 9", "type": "text"},
    "VALMAX9": {"placeholder": "[VALMAX9]", "label": "Valor Máximo 9", "type": "text"},
    "DESVI9": {"placeholder": "[DESVI9]", "label": "Desviación 9", "type": "text"},
    "MEDICI10": {"placeholder": "[MEDICI10]", "label": "Punto de Medición 10", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNI10": {"placeholder": "[UNI10]", "label": "Unidad 10", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "VALMIN10": {"placeholder": "[VALMIN10]", "label": "Valor Mínimo 10", "type": "text"},
    "VALMAX10": {"placeholder": "[VALMAX10]", "label": "Valor Máximo 10", "type": "text"},
    "DESVI10": {"placeholder": "[DESVI10]", "label": "Desviación 10", "type": "text"},

    # 5. RESULTADOS (up to 10)
    "PUNTODE1": {"placeholder": "[PUNTODE1]", "label": "Punto de Medición 1", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNIC1": {"placeholder": "[UNIC1]", "label": "Unidad 1", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "TEMPE1": {"placeholder": "[TEMPE1]", "label": "Temperatura final 1", "type": "text"},
    "RESULT1": {"placeholder": "[RESULT1]", "label": "Resultado 1", "type": "dropdown", "options": RESULT_OPTIONS},
    "PUNTODE2": {"placeholder": "[PUNTODE2]", "label": "Punto de Medición 2", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNIC2": {"placeholder": "[UNIC2]", "label": "Unidad 2", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "TEMPE2": {"placeholder": "[TEMPE2]", "label": "Temperatura final 2", "type": "text"},
    "RESULT2": {"placeholder": "[RESULT2]", "label": "Resultado 2", "type": "dropdown", "options": RESULT_OPTIONS},
    "PUNTODE3": {"placeholder": "[PUNTODE3]", "label": "Punto de Medición 3", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNIC3": {"placeholder": "[UNIC3]", "label": "Unidad 3", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "TEMPE3": {"placeholder": "[TEMPE3]", "label": "Temperatura final 3", "type": "text"},
    "RESULT3": {"placeholder": "[RESULT3]", "label": "Resultado 3", "type": "dropdown", "options": RESULT_OPTIONS},
    "PUNTODE4": {"placeholder": "[PUNTODE4]", "label": "Punto de Medición 4", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNIC4": {"placeholder": "[UNIC4]", "label": "Unidad 4", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "TEMPE4": {"placeholder": "[TEMPE4]", "label": "Temperatura final 4", "type": "text"},
    "RESULT4": {"placeholder": "[RESULT4]", "label": "Resultado 4", "type": "dropdown", "options": RESULT_OPTIONS},
    "PUNTODE5": {"placeholder": "[PUNTODE5]", "label": "Punto de Medición 5", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNIC5": {"placeholder": "[UNIC5]", "label": "Unidad 5", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "TEMPE5": {"placeholder": "[TEMPE5]", "label": "Temperatura final 5", "type": "text"},
    "RESULT5": {"placeholder": "[RESULT5]", "label": "Resultado 5", "type": "dropdown", "options": RESULT_OPTIONS},
    "PUNTODE6": {"placeholder": "[PUNTODE6]", "label": "Punto de Medición 6", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNIC6": {"placeholder": "[UNIC6]", "label": "Unidad 6", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "TEMPE6": {"placeholder": "[TEMPE6]", "label": "Temperatura final 6", "type": "text"},
    "RESULT6": {"placeholder": "[RESULT6]", "label": "Resultado 6", "type": "dropdown", "options": RESULT_OPTIONS},
    "PUNTODE7": {"placeholder": "[PUNTODE7]", "label": "Punto de Medición 7", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNIC7": {"placeholder": "[UNIC7]", "label": "Unidad 7", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "TEMPE7": {"placeholder": "[TEMPE7]", "label": "Temperatura final 7", "type": "text"},
    "RESULT7": {"placeholder": "[RESULT7]", "label": "Resultado 7", "type": "dropdown", "options": RESULT_OPTIONS},
    "PUNTODE8": {"placeholder": "[PUNTODE8]", "label": "Punto de Medición 8", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNIC8": {"placeholder": "[UNIC8]", "label": "Unidad 8", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "TEMPE8": {"placeholder": "[TEMPE8]", "label": "Temperatura final 8", "type": "text"},
    "RESULT8": {"placeholder": "[RESULT8]", "label": "Resultado 8", "type": "dropdown", "options": RESULT_OPTIONS},
    "PUNTODE9": {"placeholder": "[PUNTODE9]", "label": "Punto de Medición 9", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNIC9": {"placeholder": "[UNIC9]", "label": "Unidad 9", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "TEMPE9": {"placeholder": "[TEMPE9]", "label": "Temperatura final 9", "type": "text"},
    "RESULT9": {"placeholder": "[RESULT9]", "label": "Resultado 9", "type": "dropdown", "options": RESULT_OPTIONS},
    "PUNTODE10": {"placeholder": "[PUNTODE10]", "label": "Punto de Medición 10", "type": "dropdown", "options": PUNTO_OPTIONS},
    "UNIC10": {"placeholder": "[UNIC10]", "label": "Unidad 10", "type": "dropdown", "options": UNIDAD_OPTIONS},
    "TEMPE10": {"placeholder": "[TEMPE10]", "label": "Temperatura final 10", "type": "text"},
    "RESULT10": {"placeholder": "[RESULT10]", "label": "Resultado 10", "type": "dropdown", "options": RESULT_OPTIONS},

    # 7. FOTOGRAFIAS (up to 10)
    "IMAGE3": {"placeholder": "[IMAGE3]", "label": "Imagen 3", "type": "file"},
    "TITLE3": {"placeholder": "[TITLE3]", "label": "Título 3", "type": "text"},
    "IMAGE4": {"placeholder": "[IMAGE4]", "label": "Imagen 4", "type": "file"},
    "TITLE4": {"placeholder": "[TITLE4]", "label": "Título 4", "type": "text"},
    "IMAGE5": {"placeholder": "[IMAGE5]", "label": "Imagen 5", "type": "file"},
    "TITLE5": {"placeholder": "[TITLE5]", "label": "Título 5", "type": "text"},
    "IMAGE6": {"placeholder": "[IMAGE6]", "label": "Imagen 6", "type": "file"},
    "TITLE6": {"placeholder": "[TITLE6]", "label": "Título 6", "type": "text"},
    "IMAGE7": {"placeholder": "[IMAGE7]", "label": "Imagen 7", "type": "file"},
    "TITLE7": {"placeholder": "[TITLE7]", "label": "Título 7", "type": "text"},
    "IMAGE8": {"placeholder": "[IMAGE8]", "label": "Imagen 8", "type": "file"},
    "TITLE8": {"placeholder": "[TITLE8]", "label": "Título 8", "type": "text"},
    "TITLE9": {"placeholder": "[TITLE9]", "label": "Título 9", "type": "text"},
    "IMAGE9": {"placeholder": "[IMAGE9]", "label": "Imagen 9", "type": "file"},
    "TITLE10": {"placeholder": "[TITLE10]", "label": "Título 10", "type": "text"},
    "IMAGE10": {"placeholder": "[IMAGE10]", "label": "Imagen 10", "type": "file"},
    "TITLE11": {"placeholder": "[TITLE11]", "label": "Título 11", "type": "text"},
    "IMAGE11": {"placeholder": "[IMAGE11]", "label": "Imagen 11", "type": "file"},
    "TITLE12": {"placeholder": "[TITLE12]", "label": "Título 12", "type": "text"},
    "IMAGE12": {"placeholder": "[IMAGE12]", "label": "Imagen 12", "type": "file"},
}
